### ISSUE TITLE
 For PDF/UA-1, all fonts, even the base 14 fonts, have to be embedded! Offending font: /Times-Roman

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-samples-cc#16]
```
org.apache.fop.pdf.PDFConformanceException: For PDF/UA-1, all fonts, even the base 14 fonts, have to be embedded! Offending font: /Times-Roman
	at org.apache.fop.pdf.PDFFont.validate(PDFFont.java:172)
	at org.apache.fop.pdf.PDFFont.output(PDFFont.java:179)
	at org.apache.fop.pdf.PDFDocument.outputIndirectObject(PDFDocument.java:1055)
	at org.apache.fop.pdf.PDFDocument.streamIndirectObject(PDFDocument.java:1020)
	at org.apache.fop.pdf.PDFLinearization.writePage1(PDFLinearization.java:378)
	at org.apache.fop.pdf.PDFLinearization.writeObjects(PDFLinearization.java:320)
	at org.apache.fop.pdf.PDFLinearization.outputPages(PDFLinearization.java:269)
	at org.apache.fop.render.pdf.PDFContentGenerator.flushPDFDoc(PDFContentGenerator.java:153)
	at org.apache.fop.render.pdf.PDFDocumentHandler.endDocument(PDFDocumentHandler.java:189)
	at org.apache.fop.render.intermediate.util.IFDocumentHandlerProxy.endDocument(IFDocumentHandlerProxy.java:187)
	at org.apache.fop.render.intermediate.IFRenderer.stopRenderer(IFRenderer.java:295)
	at org.apache.fop.area.RenderPagesModel.endDocument(RenderPagesModel.java:265)
	at org.apache.fop.area.AreaTreeHandler.endDocument(AreaTreeHandler.java:342)
	at org.apache.fop.fo.DelegatingFOEventHandler.endDocument(DelegatingFOEventHandler.java:94)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endDocument(FO2StructureTreeConverter.java:124)
	at org.apache.fop.fo.FOTreeBuilder.endDocument(FOTreeBuilder.java:170)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endDocument(TransformerIdentityImpl.java:963)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(AbstractSAXParser.java:745)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:149)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:204)

  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.3/lib/metanorma/output/xslfo.rb:14:in `convert'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-csd-1.3.20/lib/isodoc/csd/pdf_convert.rb:23:in `convert'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-csd-1.3.20/lib/metanorma/csd/processor.rb:40:in `output'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:208:in `block in process_extensions'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:199:in `each'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:199:in `process_extensions'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:20:in `compile'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.11.1/lib/metanorma/cli/compiler.rb:41:in `compile_file'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.11.1/lib/metanorma/cli/compiler.rb:29:in `compile'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.11.1/lib/metanorma/cli/compiler.rb:33:in `compile'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.11.1/lib/metanorma/cli/command.rb:35:in `compile'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.11.1/lib/metanorma/cli.rb:60:in `start'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.11.1/exe/metanorma:20:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/metanorma:23:in `load'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/metanorma:23:in `<top (required)>'
```

**Comment by CAMOBAP** [comment]
cc @ronaldtse @Intelligent2013 is the problem in the adoc or in mn toolchain?

**Comment by ronaldtse** [comment]
The problem is that Times New Roman is not installed. @Intelligent2013 is working on an update that will produce degraded output if the fonts are not around. However, in this case installing Times New Roman is the best choice.

**Comment by Intelligent2013** [comment]
> The problem is that Times New Roman is not installed. @Intelligent2013 is working on an update that will produce degraded output if the fonts are not around. However, in this case installing Times New Roman is the best choice.

@ronaldtse No, the problem is that somewhere (I think in SVG) was specified font 'Times-Roman' instead of 'Times New Roman'.
@CAMOBAP795 In https://github.com/metanorma/mn2pdf/issues/27 I've fixed this issue yesterday. Please use latest release: https://github.com/metanorma/mn2pdf/releases/download/v1.11/mn2pdf-1.11.jar
